services:
  meshtastic-node-list:
    container_name: meshcore-node-list
    build: 
      context: ./flask-app
    ports:
      - "5050:5050"
    environment:
      - SECRET_KEY=this-key-is-secret-then
      - MESH_SERIAL_DEVICE=/dev/ttyACM0
      - node_data_file="/app/node_data/nodes.json"
      - message_data_file="/app/node_data/node_messages.txt"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - /home/james/meshcore-node-list/node_data:/app/node_data
      - ./logs:/app/logs
      # - ./flask-app/static:/app/static
    restart: unless-stopped  # Add restart policy